### ISSUE TITLE
Getting Css error 

### ISSUE THREAD

**Issue by ashishkumarjaiswal** [lifinance/widget#114]
I am getting this Css error while integrating with nextJs/ReactJs

[dev:frontend] - error ../../node_modules/@lifi/widget/fonts/inter.css
[dev:frontend] Global CSS cannot be imported from within node_modules.
[dev:frontend] Read more: https://nextjs.org/docs/messages/css-npm
[dev:frontend] Location: ../../node_modules/@lifi/widget/index.js
[dev:frontend] 
[dev:frontend] Import trace for requested module:
[dev:frontend] ../../node_modules/@lifi/widget/fonts/inter.css
[dev:frontend] ../../node_modules/@lifi/widget/index.js
[dev:frontend] ./src/components/Lifi/Widget.tsx

**Comment by chybisov** [comment]
Hey 👋 Have you checked documentation https://docs.li.fi/integrate-li.fi-widget/next.js-compatibility ?
