### ISSUE TITLE
okx.svg is using an uncommon attribute xmlns:xodm 

### ISSUE THREAD

**Issue by ftan-ansible** [lifinance/widget#128]
okx.svg is using an uncommon attribute xmlns:xodm which is causing an issue when this svg is being imported

```
error - ../../node_modules/@lifi/wallet-management/walletIcons/okx.svg
SyntaxError: unknown: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.
```

**Comment by chybisov** [comment]
@ftan-ansible hey, thanks for reporting this. Could you please provide details on your environment setup? (bundler etc.)

**Comment by chybisov** [comment]
Released a fix, please check it out 🙂

**Comment by ftan-ansible** [comment]
Thank you, it's fixed!

**Comment by ftan-ansible** [comment]
Thank you, it's fixed!
