### ISSUE TITLE
AwaitRenderStatus is not defined in production with nextjs

### ISSUE THREAD

**Issue by jiayuxiaochaoren** [lifinance/widget#132]
nextjs version: 13.1.6,
"react-dom": "^18.2.0",
"@types/node": "^18.7.11",
"@types/react": "^18.0.28",
"typescript": "5.1.6"
<img width="936" alt="image" src="https://github.com/lifinance/widget/assets/12232001/20d910b5-9d61-454c-a361-c37768613b56">

**Comment by beinoriusju** [comment]
I've had the exact same issue with **AwaitRenderStatus** error that started occurring just last week. My intuition says that some lib in the chain of dependencies of Nextjs dependencies got updated and this caused a memory leak inside app.

My plan was to load ReactAdmin component dynamically  (just like you load  `lifi/widget`). While in development it worked it became unusually slow (to a degree tests started failing). But when build for production it stopped working all-together giving AwaitRenderStatus error.

Unfortunately I was not able to resolve it neither with nextjs@13.2.4 nor nextjs@13.1.6, but **upgrading to 13.5.2 solved** this problem.

**Comment by chybisov** [comment]
@beinoriusju thank you for providing such a detailed insight! 🙏 @jiayuxiaochaoren I hope that helps 🙂
