### ISSUE TITLE
The widget crashes in my React v18 app - interpolating a keyframe declaration (iSKUCl) into an untagged string

### ISSUE THREAD

**Issue by paintoshi** [lifinance/widget#134]
I did test the widget in a clean React v18 project successfully, both with create-react-app and react-app-rewired. But I have a lot more dependencies in my production app (which is also React 18), and it seems it is related to styled-components, which I have installed.

Tried with both v5 and v6 of styled-components with no luck. This is the error from the chrome console, I don't know how to get past this. Downgrading to v3 will result in other incompatibilities with the app.

------------
error.ts:32 Uncaught Error: It seems you are interpolating a keyframe declaration (iSKUCl) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\`\` helper which ensures the styles are injected correctly. See https://www.styled-components.com/docs/api#css

react-dom.development.js:18687 The above error occurred in the <ThemeProvider> component:
    at ThemeProvider (bundle.js:170672:5)
    at SDKProvider (bundle.js:170603:5)
    at WidgetProvider (bundle.js:170927:5)
    at RouteExecutionStoreProvider (bundle.js:171296:5)
    at ChainOrderStoreProvider (bundle.js:171067:5)
    at HeaderStoreProvider (bundle.js:171214:5)
    at SplitSubvariantStoreProvider (bundle.js:171956:5)
    at StoreProvider (bundle.js:171023:5)
    at QueryClientProvider (bundle.js:462091:5)
    at AppProvider (bundle.js:125935:5)

![image](https://github.com/lifinance/widget/assets/88572775/8a2b0258-7e2b-4dbd-b516-f23cafec0944)

Further tracing from the console:
node_modules/@lifi/widget/providers/ThemeProvider/ThemeProvider.js
![image](https://github.com/lifinance/widget/assets/88572775/6e2b10b3-9738-41b2-9f58-d04dc4a54672)

node_modules/@lifi/widget/config/theme.js
![image](https://github.com/lifinance/widget/assets/88572775/2335cb25-10db-4211-aa71-9199fde23626)

**Comment by chybisov** [comment]
We don't use `styled-components`, but instead use `emotion`. Maybe they have compatibility issues 👀 I'll try to take a look

**Comment by chybisov** [comment]
@paintoshi should be fixed in [v2.6.0](https://github.com/lifinance/widget/releases/tag/v2.6.0), please upgrade 🙂

**Comment by paintoshi** [comment]
> @paintoshi should be fixed in [v2.6.0](https://github.com/lifinance/widget/releases/tag/v2.6.0), please upgrade 🙂

I've updated to 2.6.0 but unfortunately seeing the same error. I have not been able to replicate the issue in some demo app yet, only in production code which I cannot share.

![image](https://github.com/lifinance/widget/assets/88572775/98928d51-1bc9-447b-94fe-578a59687d30)

![image](https://github.com/lifinance/widget/assets/88572775/18dd1fcf-2f6a-41a1-b4a7-c77c1cdf3866)

**Comment by chybisov** [comment]
@paintoshi can you please share the detailed error as you did above with the information in which component the error occurred?

**Comment by paintoshi** [comment]
@chybisov Sure. 
![image](https://github.com/lifinance/widget/assets/88572775/81830d67-804f-40d0-8917-b222c88f8d15)

**Comment by chybisov** [comment]
@paintoshi Thanks, I think I found the issue and it was a tricky one. 😄 Please try v2.6.1

**Comment by paintoshi** [comment]
> @paintoshi Thanks, I think I found the issue and it was a tricky one. 😄 Please try v2.6.1

I'm impressed you managed to fix that one. I can happily report that it now loads in our app! Now I just have to figure out how this widget will interact with our current wallet integration. Thank you!

**Comment by chybisov** [comment]
@paintoshi glad to hear that 🥳 Shoot us a message in Discord if you have any other questions with integration.
