### ISSUE TITLE
Web App crash in production 

### ISSUE THREAD

**Issue by MadhavPatel1810** [lifinance/widget#140]
I have implemented this library in my React project. I used the latest version (v2.5.1) of this library.Instead of using typescript, I converted to JS,

but in that case, if I test the functionality on my local it working as expected.

but when I deployed the code to the production server the web app crashed.
![Screenshot 2023-10-11 at 12 14 19 PM](https://github.com/lifinance/widget/assets/86973682/0ad821bf-0558-4771-b50f-40b7986d22a5)

I tried to resolve the error by **downgrading** the version **(v1.32.8)** of the library, And that worked for us.

 **v1.32.8** above this version, In all the versions I faced this error. 

So can you please let me know, How can I get rid of this?

**Comment by chybisov** [comment]
@MadhavPatel1810, which tool do you use to build your app for production? Vite, CRA, webpack directly, etc?

**Comment by MadhavPatel1810** [comment]
@chybisov Thank you for your response I am using CRA. My react version is "^18.2.0".

**Comment by chybisov** [comment]
@MadhavPatel1810, which version? We had one more similar request and it seems that CRA can't manage BigInt due to the age of that tool. 😄 Would you consider upgrading to something more modern like Vite?

**Comment by MadhavPatel1810** [comment]
@chybisov, OK got it, Thank you for the help. Upgrading our project's build tool is definitely a consideration worth exploring. Vite, being a more modern build tool, could potentially address the BigInt issue.
