### ISSUE TITLE
SVG error on page reload

### ISSUE THREAD

**Issue by MedNewton** [lifinance/widget#143]
The LiFi widget works fine, but when reloading the page, there an SVG related error that comes up: 

node_modules\@lifi\wallet-management\cjs\walletIcons\alphawallet.svg:1
<svg width="100%" height="100%" viewBox="0 0 512 512" fill="none"...

SyntaxError: Unexpected token '<'

**Comment by chybisov** [comment]
@MedNewton please share your setup details 🙂 Also, please check https://docs.li.fi/integrate-li.fi-widget/next.js-compatibility
