### ISSUE TITLE
How to update or completely destroy or re-initialize the widget context config ?!

### ISSUE THREAD

**Issue by digital-flowers** [lifinance/widget#157]
We are currently working on integrating a Li-Fi widget into our Quantum wallet. However, we are encountering an issue that requires us to dynamically alter certain widget configurations, specifically the `chains:{allow:[]}` property. Once this property is initially set, there seems to be no way to modify it, even if the widget is completely unmounted.

To provide more context, in our wallet, if a user adds or removes a network, we need to update the chain IDs permitted in the widget. Unfortunately, I haven't found a method to accomplish this.

Furthermore, this issue affects other functionalities in our wallet. Each account is associated with different networks, and when we switch accounts, the chain IDs are altered but not reflected in your widget.

Here is my code:

```javacript
const chainIds = useAccountChainIds();

const config:WidgetConfig = {
      integrator: "quantum",
      variant: "default",
      subvariant: "default",
      subvariantOptions: "swap",
      appearance: "light",
      hiddenUI: ["language", "appearance", "history"],
      languages: {
        default: "en",
      },
      chains: {
        allow: chainIds,
      },
      walletManagement: signer ? {
            signer,
            connect: async () => {
              return signer;
            },
            disconnect: async () => {},
          }
        : undefined,
    }
};

return <LiFiWidget integrator={widgetConfig.integrator} config={widgetConfig} />;

```

and here are the use case:

**Account 2:**

<img width="150" alt="Screenshot 2023-11-24 at 2 00 35 AM" src="https://github.com/lifinance/widget/assets/5216291/da28ce1b-f716-4ba8-bb74-99c7b324d019">

<img width="150" alt="Screenshot 2023-11-24 at 2 00 48 AM" src="https://github.com/lifinance/widget/assets/5216291/eb543b69-e1c2-48ee-9d7a-7e85df8ed24d">

Switch to
 **Account 1:**

<img width="150" alt="Screenshot 2023-11-24 at 2 01 01 AM" src="https://github.com/lifinance/widget/assets/5216291/9ed7b734-5be7-4555-97d9-d04b70220dcb">

<img width="150" alt="Screenshot 2023-11-24 at 2 01 11 AM" src="https://github.com/lifinance/widget/assets/5216291/9b2da81f-f1ca-44d4-be46-f2ba9ebf9ff1">

**Comment by chybisov** [comment]
@digital-flowers hey, it should be fixed in `v2.9.4`. Please try it 🙂
