### ISSUE TITLE
The Widget Provider is lowercasing the passed fromToken and toToken addresses internally

### ISSUE THREAD

**Issue by digital-flowers** [lifinance/widget#165]
Hey everyone , 

The issue is that we use the events to store the user selected token internally but when we set it back to the widget the widget doesn't recognize the token balance, and when i look into the code it seems the `WidgetProvider` internally lowercasing the `fromToken` and `toToken` addresses but the `useTokenAddressBalance` hook looks for the token address in a case sensitive approach.

Also it seems that this issue is already fixed in your version 3 alpha but can we apply this fix also on the current version 2? just remove the `toLowercase()` from the `WidgetProvider`.

Thank and sorry for the headache :)

**Comment by chybisov** [comment]
@digital-flowers hey, should fixed in v2.9.5 🙂

**Comment by digital-flowers** [comment]
@chybisov thank you, awesome work  :)
