### ISSUE TITLE
Enabled Bridges showing swap form

### ISSUE THREAD

**Issue by eisenheim94** [lifinance/widget#177]
I have a problem, that widget started to show swap form when I'm navigating to Enabled Bridges setting:

<img width="447" alt="image" src="https://github.com/lifinance/widget/assets/2355948/d75f66f4-d82e-4268-a572-07ea01814d47">

What I can provide to you for more information?

**Comment by chybisov** [comment]
@eisenheim94 hey, can you please provide a reproducible example or describe the steps/configuration to reproduce it?

**Comment by eisenheim94** [comment]
@chybisov Just solved it. I had route handler for `/swap/:from/:to` to handle `0x...` addresses in route and then redirect to Swap with parameters, but handled it without react-router. Sorry for disturbing.

Your widget is really amazing, thanks for a such good product 🇺🇦
