### ISSUE TITLE
Hello, are there any examples used in nuxt3?

### ISSUE THREAD

**Issue by alphajn** [lifinance/widget#191]
Hello, are there any examples used in nuxt3?

**Comment by chybisov** [comment]
Hi, we have a Vue example here https://github.com/lifinance/widget/tree/main/examples/vue and we haven't had a chance to prepare Nuxt3 one yet.

**Comment by alphajn** [comment]
Add a plugin and write the following code

import { LiFiWidget } from '@lifi/widget';
import { applyPureReactInVue } from 'veaury';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component('SwapWidget', applyPureReactInVue(LiFiWidget));
});

**Comment by chybisov** [comment]
> Add a plugin and write the following code
> 
> import { LiFiWidget } from '@lifi/widget'; import { applyPureReactInVue } from 'veaury';
> 
> export default defineNuxtPlugin((nuxtApp) => { nuxtApp.vueApp.component('SwapWidget', applyPureReactInVue(LiFiWidget)); });

Is it a suggestion or do you have any issues integrating into Nuxt? 🙂

**Comment by alphajn** [comment]
This is to solve the problem of using a method that does not support ssr in nuxt3. I hope to see the use of demo that supports ssr.

**Comment by chybisov** [comment]
Thank you. The Widget doesn't support real SSR, as most crypto libs are client-based. It can be integrated into SSR environments such as Next.js and rendered as a client component there. It could work for Nuxt in the same way.

**Comment by chybisov** [comment]
@alphajn hey, we've added a Nuxt example here https://github.com/lifinance/widget/tree/main/examples/nuxt 
Please take a look and let us know if you have any issues. Thank you!

cc @DNR500
