### ISSUE TITLE
When applying border radius we have MUI styling on Chrome (See picture)

### ISSUE THREAD

**Issue by nini430** [lifinance/widget#215]
![image](https://github.com/lifinance/widget/assets/105129369/45db073b-e553-487d-b91b-b445b8e226fe)

**Comment by chybisov** [comment]
Can you please share more details, especially code example would be helpful

**Comment by nini430** [comment]
`<LiFiWidget config={widgetConfig} integrator="something" />
`

and inside the config we apply border-radius like this:
`
containerStyle: {
        width: '385px',
        borderRadius: 'var(--space-2)',
      },
      `
  and only in google chrome, behind the container we can see the background with different color. 

`

**Comment by chybisov** [comment]
The Widget v3 has been released. Please see the documentation here https://docs.li.fi/integrate-li.fi-widget/li.fi-widget-overview
