### ISSUE TITLE
When chain list size is 10, widget will show a +1 button when is not needed

### ISSUE THREAD

**Issue by miguilimzero** [lifinance/widget#218]
The widget currently shows a `+1` button to show all chains available when not needed. If your chain list has a size of 10, you will see the following listing:

![image](https://github.com/lifinance/widget/assets/35383529/aab284fb-6b45-41bc-8cdc-e4807fbdcb57)

However, the +1 button is not needed here. The 10th chain could already be listed on this screen, and the +1 would not exist.

**Comment by chybisov** [comment]
@miguilimzero thank you, nice catch. We will fix that 🙂
