### ISSUE TITLE
Drawer variant does not have an option to style the absolute button positioning

### ISSUE THREAD

**Issue by HugaidaS** [lifinance/widget#219]
**Problem**: The drawer variant of the widget does not contain any documentation or an option to adjust the positioning of the button, thus styles are a bit off.

**Solution**: When the chosen variant is a drawer - enable an additional field for button styles or positioning.

![Screenshot 2024-03-25 at 6 32 01 PM](https://github.com/lifinance/widget/assets/48504377/1f806ead-c594-439f-ab37-a707f40ba82a)

**Comment by chybisov** [comment]
@HugaidaS hey, thank you for filing the issue. Starting with v3 there won't be a default button to open/close the drawer. Instead, we suggest the next: 

1) Implement the button to open and close the drawer
2) Provide a `ref` to the widget so you can have access to `ref.current.openDrawer()`/`ref.current.closeDrawer()` functions

In v2 you can hide a button using `hiddenUI: [HiddenUI.DrawerButton]` option.

Please let me know if you have any questions.

**Comment by HugaidaS** [comment]
@chybisov Hi! Thanks for the clarification. Understood.
