### ISSUE TITLE
Next.js 14 incompatibility issue - OpenSea Seaport missing

### ISSUE THREAD

**Issue by westonnelson** [lifinance/widget#229]
When attempting to deploy the widget in a Next.js 14 app to Vercel, the build is failing with an error:

`@opensea/seaport-js@npm:4.0.0 STDERR command not found:`

![image](https://github.com/lifinance/widget/assets/29180454/30448e1e-5d4d-473a-84ef-877044ba3035)

**Comment by chybisov** [comment]
Can you please share more details? `@lifi/widget` doesn't have `@opensea/seaport-js` in dependencies.

**Comment by westonnelson** [comment]
> Can you please share more details? `@lifi/widget` doesn't have `@opensea/seaport-js` in dependencies.

Hey @chybisov - I tried a few different things with the updated dependencies, but still having issues deploying the app to Vercel.

I wonder if it is a TypeScript issue - the error now is showing that `container` does not exist in the `ThemeConfig` type, which I believe is imported from the @lifi/widget package. 

I hope this is helpful, let me know if there is anything else I might be able to troubleshoot!

![image](https://github.com/lifinance/widget/assets/29180454/6db8bcc6-28e8-4c8f-b3ac-6c1db1c0e864)

**Comment by chybisov** [comment]
@westonnelson In the v3 the type is called `WidgetTheme`. Which version do you use?

**Comment by westonnelson** [comment]
Whichever is the most current from the Li.Fi repository.

Basically, I'm just testing the process of integrating the widget into multiple demo apps each with different frameworks, and this is the issue I keep facing.

I can view my app locally and interact with it but not sure where the build is failing (I believe it must be breaking somewhere on the production deployment). Any other insights? Ty!

**Comment by chybisov** [comment]
@westonnelson are you trying to deploy one of the projects directly from the repository? 

The best approach is to use `@lifi/widget@alpha` package from NPM, not directly code from the repository. For example, you should be able to successfully build and deploy projects from the [examples](https://github.com/lifinance/widget/tree/main/examples) folder. If that is not the case, please let us know which one we should check.

Also, some reproducible examples from your side would be helpful in finding and better understanding the issue. Thank you! 🙂

**Comment by chybisov** [comment]
The Widget v3 has been released. Please see the documentation here https://docs.li.fi/integrate-li.fi-widget/li.fi-widget-overview
