### ISSUE TITLE
v3 does not recognize a connected wallet and is unable to connect one

### ISSUE THREAD

**Issue by haroon-schmrkow** [lifinance/widget#253]
We are using `3.0.0-alpha.41` and in production version LifiWidget is unable to recognize the connected wallet through wagmi (`^2.9.6`).

Connecting a wallet through Lifi does not work either and does not throw any exceptions.

Locally, this flow works properly, and it worked completely fine in v2.

📷 Screenshot
<img width="495" alt="image" src="https://github.com/lifinance/widget/assets/163864960/47b4d10c-a081-4e7d-8bf1-a16fee30c626">

🎥 
https://github.com/lifinance/widget/assets/163864960/e8a49f1e-1bff-4449-acee-3e956ea0969c

**Comment by chybisov** [comment]
@haroon-schmrkow hey, can you please share your setup?

**Comment by chybisov** [comment]
The Widget v3 has been released. Please see the documentation here https://docs.li.fi/integrate-li.fi-widget/li.fi-widget-overview
