### ISSUE TITLE
Can not build in Next.js 14

### ISSUE THREAD

**Issue by codeninja0415** [lifinance/widget#262]
"dependencies": {
    "@lifi/sdk": "^3.0.0-beta.0",
    "@lifi/widget": "^3.0.0-beta.1",
    "@mui/material": "5.15.19",
    "@mui/material-nextjs": "5.15.11",
    "next": "14.2.3",
    "next-themes": "^0.3.0",
    "react": "^18.3.1",
    "react-cookie": "7.1.4",
    "react-dom": "^18.3.1"
  },
  
  This is the dependencies and I got below error while building the project.
![Screenshot_4](https://github.com/lifinance/widget/assets/161300947/b447c92b-9a99-4550-8ca9-3f33f30d0cb9)

Please help me to fix this issue, Thanks

**Comment by chybisov** [comment]
@codeninja0415 please upgrade to the latest versions of the Widget and SDK packages.

**Comment by haroon-schmrkow** [comment]
@chybisov what changed in `lifi/sdk` in latest version? I am getting an error that `LiFi` is not exported from `lifi/sdk`

`import { LiFi } from "@lifi/sdk";`

**Comment by chybisov** [comment]
@codeninja0415 @haroon-schmrkow hey, sorry, I meant the latest beta versions of v3, since you are using them.

**Comment by haroon-schmrkow** [comment]
@chybisov yep, that's what I went for, `3.0.0-beta.1` of lifi/sdk, and I get that error

**Comment by codeninja0415** [comment]
@haroon-schmrkow , @chybisov , I built the project successfully by changing the tsconfig.json file like below.
After updating the "target" from **ES5** to **ES2020**, I could build the project successfully with the same version of @Lifi/SDK and @Lifi/Widget.
Thanks :)
![image](https://github.com/lifinance/widget/assets/161300947/8c014c47-5226-4ee3-8f12-2e0c63fe65d0)
