### ISSUE TITLE
Use the widget with external wallet

### ISSUE THREAD

**Issue by netanel-utila** [lifinance/widget#306]
Hi,

We are a wallet provider that want to experiment with your widget but we want to be able to communicate with the widgets directly via inputs / callbacks. For example, we want to be able to get the transaction EVM calldata and create the transaction using our API.

Do you support an external wallet client integration? I can't find useful information in the docs.

Thanks

**Comment by chybisov** [comment]
@netanel-utila Hey, does your wallet support [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963)? We use Wagmi/Viem for wallet management, and if your wallet supports the standard, the widget will detect it automatically.

Docs: https://docs.li.fi/integrate-li.fi-widget/wallet-management

**Comment by netanel-utila** [comment]
No, but I can create an adapter for this. But what about Solana? The wallet standard also supported?

**Comment by chybisov** [comment]
@netanel-utila Yes, we also support Solana Wallet Standard and auto-detect Solana wallets. Please see this section https://docs.li.fi/integrate-li.fi-widget/wallet-management#svm-wallet-connection

**Comment by netanel-utila** [comment]
One last question, I want to provide our clients a way to connect only to our addresses, I need to use the connect wallet `onConnect` feature?

**Comment by netanel-utila** [comment]
I mean can I show them a custom list of address and let the choose?

**Comment by chybisov** [comment]
@netanel-utila This will be off the widget logic managed by Wagmi/Solana-standard connectors. The widget will receive an address that is provided by those connectors. The widget doesn't manage internally to which wallet you connect.

**Comment by chybisov** [comment]
@netanel-utila happy to help. Don't hesitate to ask any questions if you have any in the process.
