### ISSUE TITLE
Syntax error (moduleAttributes)

### ISSUE THREAD

**Issue by Daron976** [lifinance/widget#310]
Hello, we have been trying to integrate the lifi widget onto our dapp, but we are facing some errors from the installed package -we've gone through the docs and tried multiples fixes with no success, could you please assist us

Our dapp is build with create react app

![Screenshot from 2024-10-08 14-53-12](https://github.com/user-attachments/assets/17bbbb6e-8b1a-417b-b7bd-3ad43878adb1)
![Screenshot from 2024-10-08 14-53-25](https://github.com/user-attachments/assets/2b33d863-81ff-4737-ae92-1d1c0070ecdf)
![Screenshot from 2024-10-08 17-26-51](https://github.com/user-attachments/assets/88a9bd42-5095-4310-8807-e8bc6595230a)
![image](https://github.com/user-attachments/assets/81b21e56-a756-4584-a5ec-82cfd5a9cae0)

**Comment by chybisov** [comment]
@Daron976 hey, we have an example here https://github.com/lifinance/widget/tree/main/examples/create-react-app but the best way is to migrate from create-react-app to Vite, because create-react-app is outdated.

**Comment by Daron976** [comment]
@chybisov 
we will look at the example closely and try again,

Thanks :+1:
