### ISSUE TITLE
MUI v5 -> v6 upgrade

### ISSUE THREAD

**Issue by Systerr** [lifinance/widget#315]
Hi. Please upgrade mui to the latest version. They introduced v6 few month ago https://mui.com/blog/material-ui-v6-is-out/ and it almost the same version without breaking changes 

Our product uses  v6 and right now out build contains two versions v5 and v6.  Will be amazing to have only one version.  Thank you!

**Comment by chybisov** [comment]
Hey, thank you! Yes, we have this in mind and will make an upgrade soon. Stay tuned :)

**Comment by varunguleriaCodes** [comment]
Hi @chybisov, can I work on this? I have reviewed the MUI v5 to v6 changes, and since the major updates components don’t impact this project, the upgrade should be straightforward. Let me know!

**Comment by chybisov** [comment]
@Systerr upgraded in #334 🥳

**Comment by Systerr** [comment]
@chybisov  Thank you!
