### ISSUE TITLE
API is failing on testnet

### ISSUE THREAD

**Issue by Ankitwasnik** [lifinance/widget#41]
Hi,

I have integrated the widget into my app. I wanted to test the functionality on the testnet. I have selected the goerli testnet as the source chain and the polygon testnet as the destination chain. I want to swap the ETH from goerli to USDC on the polygon testnet. I am getting errors from the below API.

API: https://staging.li.quest/v1/advanced/routes

Error Message: Access to XMLHttpRequest at 'https://staging.li.quest/v1/advanced/routes' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/18588492/211583195-8aaa8394-ee08-4c1f-b016-6ceaccbaa1c0.png">

I understand this error is because APIs from localhost are being blocked. Is this intentional?
How do I fix this issue?

**Comment by chybisov** [comment]
@Ankitwasnik hi, sometimes this can happen during the redeployment of the staging. Could you please try again and share if the issue is still there?

**Comment by Ankitwasnik** [comment]
Hi @chybisov. Thanks for responding.
The widget is working for goerli to goerli trasnfer. I tried transfer of goerli ETH to goerli USDC. 

But it is not working for goerli to polygon testnet transfer. I tried transfer of goerli ETH to polygon testnet WETH.

**Comment by chybisov** [comment]
@Ankitwasnik not every bridge or DEX provides enough liquidity/support their testnets. We recommend testing on cheap chains like Polygon with small amounts.

**Comment by Ankitwasnik** [comment]
@chybisov 
Please see the below screenshot.
<img width="595" alt="image" src="https://user-images.githubusercontent.com/18588492/212674343-2a32e1f0-03f5-44a0-b18a-cd8cc1074a4c.png">

I have tried almost all the pairs on the polygon testnet. Nothing is working for the polygon testnet.

**Comment by Ankitwasnik** [comment]
I can see in the documentation that LiFi is supporting the transfer of Eth on Goerli to Weth on polygon testnet. See this [link](https://docs.li.fi/integrate-li.fi-js-sdk/testing-your-integration#eth-on-goerli-to-weth-on-mumbai-via-polygon-bridge)
This does not work as well.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/18588492/212675532-570925b7-da0e-4b00-afcb-206e129c295c.png">

I want to try the cross-chain transfer. Let me know if there is any workaround. @chybisov

**Comment by chybisov** [comment]
@Ankitwasnik, when I said about Polygon, I meant Polygon Mainnet. Testnets don't have liquidity sometimes and have plenty of other issues.

**Comment by Ankitwasnik** [comment]
Ok. Thanks @chybisov
