### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by TranSonDinh** [lifinance/widget#42]
**Bug Reports**
```
./node_modules/@lifi/widget/fonts/inter.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@lifi/widget/index.js
```
I recommend to not require styles in the core. It should be included by the package consumer.

More info https://github.com/zeit/next.js/blob/master/errors/css-npm.md

**Comment by chybisov** [comment]
@TranSonDinh Hi, I assume you've closed the issue because you found our docs regarding [next.js compatibility](https://docs.li.fi/integrate-li.fi-widget/next.js-compatibility). We use that CSS for fonts, and yes, we can consider including it separately in the future 🙂
