### ISSUE TITLE
Icons doesnt render properly in chain select section  

### ISSUE THREAD

**Issue by SabariGanesh-K** [lifinance/widget#50]
You can very well see the issue here where chain icons doesnt render .
![image](https://user-images.githubusercontent.com/64348740/217307662-0698a6fc-38ae-418b-ba8e-8b6b59c36f95.png)

Error produced in console log
![image](https://user-images.githubusercontent.com/64348740/217307440-d3b01a1b-a669-46ba-86b6-e9a908363ea7.png)

**Comment by chybisov** [comment]
@SabariGanesh-K hi, could you please share a link where I can see those errors?
