### ISSUE TITLE
The widget with the variant as a drawer sometime throw a react error

### ISSUE THREAD

**Issue by mewpawee** [lifinance/widget#58]
Try the widget's example for Nextjs with the drawer variant config. The drawer sometimes renders LI.FI Swap as button.lifiSwap and throw a react error "Error: Should have a queue. This is likely a bug in React. Please file an issue." when clicked

![Screenshot 2566-02-20 at 15 41 12](https://user-images.githubusercontent.com/32890875/220058091-3ae9b896-2ffb-4e4b-9a33-b7d5fd55f7d2.png)

![Screenshot 2566-02-20 at 15 41 02](https://user-images.githubusercontent.com/32890875/220058169-c997af7f-ab3c-4e69-b31d-0c529d236cf2.png)

**Comment by chybisov** [comment]
@mewpawee hi, thank you for reporting the issue. The fix was released in `v1.32.3`. Please upgrade and check 🙂

**Comment by mewpawee** [comment]
It work like a charm :)
