### ISSUE TITLE
[Question] - How to properly configure with nextjs12?

### ISSUE THREAD

**Issue by risardi123** [lifinance/widget#64]
Currently the example is on nextjs13, but I try to adapt with nextjs12 which not work as intended. Or is it not compatible with nextjs 12

And there is strange linter error, when install "@lifi/widget": "^1.32.8":
<img width="739" alt="Screenshot 2023-03-16 at 11 20 33" src="https://user-images.githubusercontent.com/29408156/225513493-01f36484-1140-4256-8010-b31935df423c.png">

package.json:
"next": "12.1.0",
"next-transpile-modules": "^10.0.0",
"react": "17.0.2",
"swr": "^1.3.0"
"react-dom": "17.0.2",
"@lifi/sdk": "^1.7.2",
 "@lifi/widget": "^1.32.8",

**Comment by chybisov** [comment]
@risardi123 it should work fine with Next.js 12 and React 18. You use React 17, so please upgrade to the latest.
