### ISSUE TITLE
toAddress reset when selecting token

### ISSUE THREAD

**Issue by juscamarena** [lifinance/widget#68]
I believe the latest update caused this. We were on a previous version and had no issues until updating. It isn't just a visual issue either, tested a swap and it swapped to the same wallet and not the one set.

![lifi-bug](https://user-images.githubusercontent.com/446261/229370919-2930116e-869a-4d42-b28b-a3763d17585b.gif)

**Comment by juscamarena** [comment]
The issue is fixed by reverting back to the older version of the widget: "@lifi/widget": "^1.32.7"

**Comment by chybisov** [comment]
@juscamarena thank you, I'll take a look. 🙂

**Comment by chybisov** [comment]
> The issue is fixed by reverting back to the older version of the widget: "@lifi/widget": "^1.32.7"

I guess the new version you are referring to is 2.0.0-alpha-0?

I can't reproduce this issue there ([playground](https://playground.li.fi/)). Could you please provide the widget config and share more details on reproducing it? 

Thanks! 🙂
