### ISSUE TITLE
this.windowProvider?.on is not a function

### ISSUE THREAD

**Issue by sbvhev** [lifinance/widget#93]
I am getting `this.windowProvider?.on is not a function` error if we add on react project.

<LiFiWidget integrator="xx" config={widgetConfig} />

I think it's just dependency conflict especially on the wallet connection.
I am using rainbow kit provider along with react version 18.2.0.

Do you know why this happens?

**Comment by chybisov** [comment]
@sbvhev Hey, could you please share a reproducible example? 🙂

**Comment by sbvhev** [comment]
I am not sure how you can reproduce this error. You should probably use rainbow kit as an example of wallet connection and use react 18.2.0. That way, you can see that error.

**Comment by chybisov** [comment]
@sbvhev Can you at least share how you use the widget with the rainbow kit? 🙂
